export const projectList = [
  {
    imageUrl: "https://via.placeholder.com/150",
    title: "TaskOPedia",
    redirectUrl: "",
    description: "desc",
    githubUrl: "",
    youtubeUrl: "",
    topicsCovered: ["",""],
  },
  {
    imageUrl: "https://via.placeholder.com/150",
    title: "CountOPedia",
    redirectUrl: "",
    description: "desc",
    githubUrl: "",
    youtubeUrl: "",
    topicsCovered: ["",""],
  },
  {
    imageUrl: "https://via.placeholder.com/150",
    title: "ContactOPedia",
    redirectUrl: "",
    description: "desc",
    githubUrl: "",
    youtubeUrl: "",
    topicsCovered: ["",""],
  },
  {
    imageUrl: "https://via.placeholder.com/150",
    title: "WatchOPedia",
    redirectUrl: "",
    description: "desc",
    githubUrl: "",
    youtubeUrl: "",
    topicsCovered: ["",""],
  },
  {
    imageUrl: "https://via.placeholder.com/150",
    title: "LifecycleOPedia",
    redirectUrl: "",
    description: "desc",
    githubUrl: "",
    youtubeUrl: "",
    topicsCovered: ["",""],
  },
  {
    imageUrl: "https://via.placeholder.com/150",
    title: "RouteOPedia",
    redirectUrl: "",
    description: "desc",
    githubUrl: "",
    youtubeUrl: "",
    topicsCovered: ["",""],
  },
  {
    imageUrl: "https://via.placeholder.com/150",
    title: "ReduxOPedia",
    redirectUrl: "",
    description: "desc",
    githubUrl: "",
    youtubeUrl: "",
    topicsCovered: ["",""],
  },
  {
    imageUrl: "https://via.placeholder.com/150",
    title: "TravelOPedia",
    redirectUrl: "",
    description: "desc",
    githubUrl: "",
    youtubeUrl: "",
    topicsCovered: ["",""],
  },
]