export const projectList = [
  {
    imageUrl: "https://picsum.photos/200/300/",
    title: "TaskOPedia",
    description: "Learn basic fundamentals of React by building a simple page.",
    githubUrl: "https://github.com/chrismdks/taskopedia",
    topicsCovered: [
      "What is JSX",
      "Props and Components",
      "Class based Components",
      "Functional Components",
    ],
  },
  {
    imageUrl: "https://picsum.photos/200/302",
    title: "CountOPedia",
    description: "Build a simple game to attack or defense and get points.",
    githubUrl: "https://github.com/chrismdks/countopedia",
    topicsCovered: [
      "State in React",
      "Events in React",
    ],
  },
  {
    imageUrl: "https://picsum.photos/200/301",
    title: "ContactOPedia",
    description: "Perform CRUD operations on contact list in React.",
    githubUrl: "https://github.com/chrismdks/contactopedia",
    topicsCovered: [
      "Reusing Components",
      "Axios Calls",
      "Validations in React",
      "CRUD Operations",
    ],
  },
  {
    imageUrl: "https://picsum.photos/200/305",
    title: "LifecycleOPedia",
    description: "We will explore lifecycle methods in functional and class components.",
    githubUrl: "https://github.com/chrismdks/lifecyclopedia",
    topicsCovered: [
      "LifeCycle in Class Components",
      "LifeCycle in Functional Components",
      "Hooks in React",
      "Controlled Components",
      "LocalStorage State",
    ],
  },
  {
    imageUrl: "https://picsum.photos/200/306",
    title: "WatchOPedia",
    description: "We will explore more on hooks in functional components.",
    githubUrl: "https://github.com/chrismdks/watchopedia",
    topicsCovered: [
      "State in Functional Components", 
    ],
  },
  {
    imageUrl: "https://picsum.photos/200/307/",
    title: "RouteOPedia",
    description: "Explore routing in React JS.",
    githubUrl: "https://github.com/chrismdks/routeopedia",
    topicsCovered: [
      "React Router",
      "NavLink",
      "Navigation Hooks",
      "Parameterized Routing",
      "Nested Routes",
    ],
  },
  {
    imageUrl: "https://picsum.photos/200/310/",
    title: "ReduxOPedia",
    description: "Better state management using Redux Toolkit.",
    githubUrl: "https://github.com/chrismdks/reduxopedia",
    topicsCovered: [
      "Redux Store",
      "Reducers and Actions",
      "Redux Slice",
      "Multiple Slices",
      "Custom Listener",
    ],
  },
  {
    imageUrl: "https://picsum.photos/200/313/",
    title: "TravelOPedia",
    description: "Explore Redux Query and Mutation for async calls.",
    githubUrl: "https://github.com/chrismdks/travelopedia",
    topicsCovered: [
      "Redux Store",
      "Redux Toolkit Query",
      "Redux Toolkit Mutation",
      "Multiple Query",
      "Json Server",
    ],
  },
  {
    imageUrl: "https://picsum.photos/200/309/",
    title: "Red Mango API",
    description: ".NET API for restaurant with multiple endpoints.",
    githubUrl: "www.github.com",
    topicsCovered: [
      ".NET 7 API",
      "Identity Authentication & Authorization",
      "Stripe Payment Endpoint",
      "Restaurant App Endpoints",
    ],
  },
  {
    imageUrl: "https://picsum.photos/200/308/",
    title: "Red Mango Client",
    description: "Build real world project where we consume .NET API",
    githubUrl: "www.github.com",
    topicsCovered: [
      "Real world React Project",
      "Redux",
      "Redux Toolkit",
      "React Hooks",
      "Stripe React",
      "React Router",
      "Integrated .NET API",
    ],
  },
]